[package]
name = "abomonation_derive"
version = "0.1.0"
authors = ["Michael Layzell <michael@thelayzells.com>"]

[lib]
name = "abomonation_derive"
rustc-macro = true

[dependencies]
syn = "0.9"
quote = "0.3"
synstructure = "0.1"

[dev-dependencies]
abomonation = "*"
