[package]
name = "abomonation_derive"
version = "0.1.1"
authors = ["Michael Layzell <michael@thelayzells.com>"]

[lib]
name = "abomonation_derive"
proc-macro = true

[dependencies]
syn = "0.10"
quote = "0.3"
synstructure = "0.4"

[dev-dependencies]
abomonation = "*"
